export const SET_CURRENT_USER = 'SET_CURRENT_USER'
export const LOAD_POSTS = 'LOAD_POSTS'
export const SET_POSTS ='SET_POSTS'
export const ACTIVE_TAB = 'ACTIVE_TAB'
export const IMAGE_MODAL = 'IMAGE_MODAL'
export const POST_MODAL = 'POST_MODAL'
export const DELETE_POST = 'DELETE_POST'